### ISSUE TITLE
[BUG]Git push of a repository cloned with ssh does not work

### ISSUE THREAD

**Issue by omonimus1** [ForEvolve/git-extensions-for-vs-code#10]
# How to reproduce
* Clone a repository via ssh.
* Make any change you like
* Stage changes (via git extension)
* Add commit message (via git extension)
* Try to push (always via git extension).

You will receive the following error message: 
![image](https://user-images.githubusercontent.com/23085146/132124741-b794d090-b9c3-41d6-a323-5742938cf2c0.png)
![image](https://user-images.githubusercontent.com/23085146/132124754-cc306bfc-6a6a-4d9f-bad7-ed3ee0a3c746.png)

# Instead via terminal
* Instead, push the same commit via the terminal, it would ask for a password related to the ssh key.
It would be nice to ask for the password via GUI, and manage this scenario.

**Comment by Carl-Hugo** [comment]
Wrong repo; this repo is only for my VS Code plugin that adds a `Browse with Git Extensions` option in the context menu.
